project:
  type: website
  
bibliography: referencias.bib
csl: abnt.csl

website:
  page-navigation: true
  title: "Introdução a Análises Genômicas no PLINK"
  site-url: "https://paulobarros.github.io/introducao-ao-linux"
  repo-url: "https://github.com/paulobarros/curso-plink"
  repo-actions: [issue]
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "![Caption](https://raw.githubusercontent.com/paulobarros/curso-plink/8a1fe450d1a9d349ac7ec58d235748309fd786d0/images/frogbird.png){height=45}  &nbsp;  **&copy; CC-By Paulo Barros, 2023**"
    
  sidebar:
    logo: "images/logoplink.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://paulobarros.com.br
        text: "paulobarros.com.br"
      - icon: github
        href: https://github.com/paulobarros/curso-plink
        text: "Análises Genômicas no PLINK"
      - icon: twitter
        href: https://twitter.com/pbarrosjr
        text: "Paulo Barros Twitter"         

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Apresentação
      - section: genomica/index.qmd
        contents: 
          - href: genomica/markers.qmd
            text: Marcadores Moleculares
          - href: genomica/snps.qmd
            text: SNP
          - href: genomica/sequenciamento.qmd
            text: Genotipagem
          - href: genomica/aplicacao.qmd
            text: Aplicações
      - section: plink/index.qmd
        contents:
          - href: plink/datafiles.qmd
            text: Arquivos de Entrada
          - href: plink/runplink.qmd
            text: Rodando o PLINK
          - href: plink/qc.qmd
            text: Controle de Qualidade
          - href: plink/diversity.qmd
            text: Estatísticas Básicas
          - href: plink/pca.qmd
            text: PCA
          - href: plink/datasets.qmd
            text: Datasets

format:
  html:
    theme:
      light: [yeti, pbstyle.scss]
      dark: [darkly, pbstyle.scss]
    code-copy: true
    code-overflow: wrap
    code-block-bg: "#1A3434"
    code-block-border-left: "#FFF0B0"
    code-line-numbers: true
    highlight-style: dracula
    toc: true
    

execute:
  freeze: auto
  engine: knitr
