---
title: "Introdução a Análises Genômicas com PLINK"
lang: pt-BR
---

## Apresentação {#apresentacao}

Este é um curso introdutório de Análises Genômicas utilizando o software PLINK [@purcell2007plink] ministrado para o Grupo de Pesquisas em Conservação (GACOM) na Universidade Estadual do Sudoeste da Bahia (UESB), campus Jequié. O objetivo deste curso é oferecer aos alun\@s um primeiro contato com as Análises Genônicas a partir de dados de SNPs no software PLINK.

Este curso foi organizado graças a uma gama de materiais de qualidade disponíveis gratuitamente na internet, tanto em materiais disponibilizados por professores/pesquisadores bem como pelas próprias documentações do PLINK. Gostaria de mencionar também e agradecer ao excelente material do [Professor Gábor Mészáros](https://genomicsbootcamp.github.io/book/) do qual pude aproveitar excelentes recursos e insights.


## Quem ministra?

Me chamo Paulo Barros, sou Bacharel em Ciências Biológicas com ênfase em Genética pela UESB, e atualmente aluno de Mestrado no Programa de Pós-Graduação em Genética, Biodiversidade e Conservação pela UESB. Tenho atuado como Cientista de Dados na área da Biologia desde o final da graduação colaborando em trabalhos das mais diversas áreas. Também tenho experiência oferecendo cursos e mentorias em Análise de Dados com a Linguagem R para estudantes de graduação e pós-graduação, bem como para professores e profissionais de áreas correlatas da Biologia.


::: {#refs}

:::